delay: 10
feeds:
- https://www.fedscoop.com/feed
- https://portswigger.net/daily-swig/rss
- https://rssfeeds.9news.com/kusa/home
- http://feeds.denverpost.com/dp-news-breaking
- https://feeds.feedburner.com/NakedSecurity
- https://www.schneier.com/feed/atom
- http://www.nws.noaa.gov/data/current_obs/KDEN.rss
- https://www.merriam-webster.com/wotd/feed/rss2
- http://feeds.bbci.co.uk/news/world/rss.xml?edition=uk
- http://rss.cnn.com/rss/cnn_topstories.rss
- http://rss.slashdot.org/Slashdot/slashdotApple
- http://rss.slashdot.org/Slashdot/slashdotHardware
- https://us-cert.cisa.gov/ncas/all.xml
- https://www.sans.org/blog/feed.xml
- https://addons.mozilla.org/en-US/developers/feed?privaterss=96cd0dc3-3a74-b43d-b5b5-c8eda8cc356f
- https://www.netresec.com/rss.ashx
- https://nakedsecurity.sophos.com/category/apple/feed/
- https://www.intego.com/mac-security-blog/feed/
- https://feeds.feedburner.com/GoogleOnlineSecurityBlog
- https://feeds.feedburner.com/NakedSecurity
- https://what-if.xkcd.com/feed.atom
- https://threatpost.com/feed/
- https://www.fedscoop.com/feed
- https://isc.sans.edu/rssfeed.xml
- https://feeds2.feedburner.com/inkophile
- https://googleprojectzero.blogspot.com/feeds/posts/default
- https://www.wnyc.org/feeds/people/shankar-vedantam
- https://www.penaddict.com/blog?format=rss
- https://tidbits.com/feeds/tidbits_blurb.rss
- https://www.reddit.com/r/todayilearned.rss
font-family: FreeSans
font-size: 16
font-slant: roman
font-weight: normal
growright: false
reload: 120
